# Generated by Django 3.0.6 on 2020-11-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('medicaldignosis', models.CharField(max_length=1000)),
                ('medicaldignosisdate', models.DateField()),
                ('location', models.CharField(max_length=1000)),
                ('q1', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q2', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q3', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q4', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q5', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q6', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q7', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q8', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q9', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q10', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q11', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q12', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q13', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q14', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q15', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q16', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q17', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q18', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q19', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q20', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q21', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q22', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q23', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q24', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q25', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q26', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q27', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q28', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q29', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q30', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q31', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q32', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q33', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q34', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q35', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q36', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q37', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q38', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
                ('q39', models.CharField(choices=[('1', '1'), ('2', '1'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=10)),
            ],
        ),
    ]
